### ISSUE TITLE
No more communication since last tahoma API update

### ISSUE THREAD

**Issue by SlyBall912** [redbug26/jeedom-tahoma#23] opened 2019-12-04 17:43 UTC
Hi,

Since the last tahoma API update (2019-12-03), the communication from Jeedom plugin and tahoma account is NOK. 

Thanks a lot for your help !

Regards

Sylvain

**Comment by BomberX** [comment] 2019-12-04 18:55
Hi,

Confirmed: I got the same pb here !
Maybe some APIs changed from Somfy side ?

Again thanks for your support on this great plugin !

Regards

BX

**Comment by ViVaLaWeEd** [comment] 2019-12-04 19:19
Hi,

Confirmed too: Same problem since the last somfy update.

Thanks for support 

Regards

Alex

**Comment by raphaelpregnon** [comment] 2019-12-05 21:00
Hi, confirmed too: same problem
Raph

**Comment by redbug26** [comment] 2019-12-08 09:45
Fixed by @jordan-akki 
Thanks to him

**Closed as completed by redbug26** 2019-12-08 09:45 UTC
